# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df826841f492d8472f4673e036e17b6ab585e544c138f6e562cc243e4d61739d1d2e8d5ff1c5dfa2f0d39d5d6172fc50844e8ef4b2018a2b0dbfe2b8c573140d

test:
  secret_key_base: 87239e37a05035075481c493ac909065e0adbd81725813323985dee1f367005a22cd48184e60a7f8a004902122281fe63f7008490c2fb6c202890a35dfba37d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
